name: CI build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - LICENSE.txt
      - README.md
      - .dockerignore

  workflow_dispatch:

  schedule:
    - cron: '5 18 4 * *'

jobs:
  build-n-push:

    runs-on: ubuntu-latest
    env:
#      DOCKER_CONFIG: $HOME/.docker
      DIMAGE: buffertly/haproxy-quic

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Common build arguments
      run: echo "COMMON_ARGS=--progress=plain --label=org.opencontainers.image.revision=${GITHUB_SHA:0:7} --label=org.opencontainers.image.authors=$GITHUB_ACTOR --label=org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} --label=org.opencontainers.image.created=$(date -Idate) " >> $GITHUB_ENV

    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: buildx-cache
        restore-keys: |
            buildx-

    - name: Build-image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        platforms: linux/amd64
        cache-from: type=local,src=/tmp/.buildx-cache
        labels: |
            org.opencontainers.image.revision=${GITHUB_SHA:0:7}
        build-args: |
            ARG1=val1
            ARG2=val2

        tags: |
            ${DIMAGE}:action1
            ${DIMAGE}:action2

    - name: Build and push HAProxy w/ WolfSSL
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=wolfssl -t ${DIMAGE}:wolfssl --push ${COMMON_ARGS} . #--platform linux/amd64,linux/arm64/v8 .
        docker tag ${DIMAGE}:wolfssl ${DIMAGE}:latest
        docker push -q ${DIMAGE}:latest

    - name: Build and push HAProxy w/ QuicTLS
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=quictls_quictls -t ${DIMAGE}:quictls --push ${COMMON_ARGS} --platform linux/amd64 .

    - name: Build and push HAProxy w/ OpenSSL
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=quictls_openssl -t ${DIMAGE}:openssl --push ${COMMON_ARGS} . #--platform linux/amd64,linux/arm64/v8 .
        docker tag ${DIMAGE}:openssl ${DIMAGE}:stable
        docker push -q ${DIMAGE}:stable

