name: CI build

env:
  IMAGENAME: buffertly/haproxy-quic

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '5 18 4 * *'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
      IMGLABELS: "--label=org.opencontainers.image.revision=${GITHUB_SHA:0:7} --label=org.opencontainers.image.authors=$GITHUB_ACTOR --label=org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup multiarch environment
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --name multibuilder --driver docker-container --bootstrap
        docker buildx use multibuilder

    - name: Login to registry
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}

    - name: Build and push HAProxy w/ WolfSSL
      continue-on-error: true
      run: |
        docker build --progress=plain --build-arg=SSLVENDOR=wolfssl -t $IMAGENAME:wolfssl --push $IMGLABELS .
#        docker buildx build --progress=plain --platform linux/amd64,linux/arm64/v8 --build-arg=SSLVENDOR=wolfssl -t $IMAGENAME:wolfssl --push 

#    - name: Build and push HAProxy w/ QuictTLS/OpenSSL
#      continue-on-error: true
#      run: |
#        docker buildx build --progress=plain --platform linux/amd64,linux/arm64/v8 --build-arg=SSLVENDOR=quictls_openssl -t $IMAGENAME:openssl --push --label=com.github.zsbt.haproxy.commit=${LAST_COMMIT_SHA:0:7} --label=org.opencontainers.image.created="$(date -Iminutes)" --label=org.opencontainers.image.url=$IMAGENAME .

