name: build the image and publish on DockerHub

env:
  IMAGENAME: buffertly/haproxy-quic

on:
#  push:
#    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '5 18 4 * *'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: multiarch environment
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --name multibuilder --driver docker-container --bootstrap
        docker buildx use multibuilder

    - name: build and push 
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}
        docker buildx build --platform linux/amd64 --push --build_arg=SSLVENDOR=wolfssl -t $IMAGENAME:wolfssl --progress=plain --label=com.github.zsbt.haproxy.commit=${{ env.GITHUB_SHA }} --label=org.opencontainers.image.created="$(date -Iminutes)" --label=org.opencontainers.image.url=$IMAGENAME .

