name: CI build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - LICENSE.txt
      - README.md
      - .dockerignore

  workflow_dispatch:

  schedule:
    - cron: '5 18 4 * *'

jobs:
  build-n-push:

    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
      IMAGENAME: buffertly/haproxy-quic

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup multiarch environment
      run: |
        docker run --privileged --rm tonistiigi/binfmt --install all
        docker buildx create --name multibuilder --driver docker-container --bootstrap
        docker buildx use multibuilder

    - name: Login to registry
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASS }}

    - name: Common build arguments for image ${IMAGENAME}
      run: echo "COMMON_ARGS=--progress=plain --label=org.opencontainers.image.revision=${GITHUB_SHA:0:7} --label=org.opencontainers.image.authors=$GITHUB_ACTOR --label=org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} --label=org.opencontainers.image.created=$(date -Idate) " >> $GITHUB_ENV

    - name: Build and push HAProxy w/ WolfSSL
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=wolfssl -t ${IMAGENAME}:wolfssl --platform linux/amd64,linux/arm64/v8 --push ${COMMON_ARGS} .
        docker tag ${IMAGENAME}:wolfssl ${IMAGENAME}:latest
        docker push -q ${IMAGENAME}:latest

    - name: Build and push HAProxy w/ QuicTLS
      #continue-on-error: true
      run: |
        docker build --build-arg=SSL_VENDOR=quictls_quictls -t ${IMAGENAME}:quictls --push ${COMMON_ARGS} .

    - name: Build and push HAProxy w/ OpenSSL
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=quictls_openssl -t ${IMAGENAME}:openssl --platform linux/amd64,linux/arm64/v8 --push ${COMMON_ARGS} .
        docker tag ${IMAGENAME}:openssl ${IMAGENAME}:stable
        docker push -q ${IMAGENAME}:stable

