name: CI build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - LICENSE.txt
      - README.md
      - .dockerignore

  workflow_dispatch:

  schedule:
    - cron: '5 18 4 * *'


jobs:
  build-n-push:

    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
      DIMAGE: buffertly/haproxy-quic

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Common build arguments
      run: echo "COMMON_ARGS=--progress=plain --label=org.opencontainers.image.revision=${GITHUB_SHA:0:7} --label=org.opencontainers.image.authors=$GITHUB_ACTOR --label=org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} --label=org.opencontainers.image.created=$(date -Idate) " >> $GITHUB_ENV

    - name: Build and push HAProxy w/ WolfSSL
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=wolfssl -t ${DIMAGE}:wolfssl -t ${DIMAGE}:latest --push ${COMMON_ARGS} . #--platform linux/amd64,linux/arm64/v8 .

    - name: Build and push HAProxy w/ QuicTLS
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=quictls_quictls -t ${DIMAGE}:quictls --push ${COMMON_ARGS} --platform linux/amd64 .

    - name: Build and push HAProxy w/ OpenSSL
      #continue-on-error: true
      run: |
        docker buildx build --build-arg=SSL_VENDOR=quictls_openssl -t ${DIMAGE}:openssl -t ${DIMAGE}:stable --push ${COMMON_ARGS} . #--platform linux/amd64,linux/arm64/v8 .

